### ISSUE TITLE
当有虚拟按键时，用夜间模式会看不到，因为地下虚拟按键背景变成白色了，导致按钮看不到了？

### ISSUE THREAD

**Issue by ziyouxiaozi** [lenebf/AppDress#1]

**Comment by weichaoIO** [comment]
@Override
    public boolean excludeView(@NonNull View view) {
        return (view instanceof ImageView)
                || view.getId() == android.R.id.navigationBarBackground
                || view.getId() == android.R.id.statusBarBackground;
    }

**Comment by xiaolf1** [comment]
> ```
> @Override
> public boolean excludeView(@NonNull View view) {
>     return (view instanceof ImageView)
>             || view.getId() == android.R.id.navigationBarBackground
>             || view.getId() == android.R.id.statusBarBackground;
> }
> ```

这个方案可以解决你的问题，谢谢 @weichao66666
