### ISSUE TITLE
原始状态恢复异常

### ISSUE THREAD

**Issue by LGlxb** [lenebf/AppDress#2]
设置中引用此Moudle,设置主题后,保存选项.啥死进程后,打开记录无误,恢复原始异常

**Comment by xiaolf1** [comment]
没太明白你的意思。调用 AppDress.wear(this) 只是相当于初始化，要着色，需要调用  AppDress.tint 方法

**Comment by LGlxb** [comment]
如我将状态保存为护眼模式,并保存此状态杀死.重新启动APP  AppDress.tint(null)会失效

**Comment by xiaolf1** [comment]
> 如我将状态保存为护眼模式,并保存此状态杀死.重新启动APP AppDress.tint(null)会失效

AppDress.tint(null) 就是还原成原始状态的意思，你保存的是什么颜色，就需要染成什么颜色，比如你保存的是护眼色，那么应用启动时应该调用AppDress.tint(new EyeProtectionColor())着色

**Comment by xiaolf1** [comment]
@LGlxb 问题是否解决了，如果解决了，我把这个issues关掉了。
