### ISSUE TITLE
深色模式 下，彩色 怎么避免 更改呢？

### ISSUE THREAD

**Issue by fy310518** [lenebf/AppDress#3]

**Comment by xiaolf1** [comment]
@fy310518 可以参考 https://www.yuque.com/lenebf/fl1svo/sagoxt 这篇文章，原理和反色模式不包含ImageView一样，对要排除的View施加逆矩证，后续版本更新会加入。

**Comment by xiaolf1** [comment]
> ~~@fy310518 可以参考 https://www.yuque.com/lenebf/fl1svo/sagoxt 这篇文章，原理和反色模式不包含ImageView一样，对要排除的View施加逆矩证，后续版本更新会加入。~~

抱歉，试了下，黑白模式使用的矩阵没有逆矩证，所以无法对View进行还原操作。
